---
- hosts: lbs
  remote_user: "{{ remote_user }}"
  become: yes

  tasks:
  - name: "Set authorized key for {{ remote_user }} copying it from current user"
    authorized_key:
      user: "{{ remote_user }}"
      state: present
      key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
      manage_dir: yes
    #notify: restart sshd
    register: sshd_auth
  - name: restart sshd if need
    service:
      name: sshd
      state: restarted
    when: sshd_auth.changed
  - name: allow sudo without password
    lineinfile:
      path: /etc/sudoers
      state: present
      regex: '^%{{ remote_user }}'
      line: '%{{ remote_user }} ALL=(ALL:ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'

  #roles:
  #- load-balancers

...
