---
all:
  hosts:
    loadbalancers:
      hosts:
        node1:
          vrrp_state: MASTER
          vrrp_priority: 100
          vrrp_interface: "{{ ansible_eth0 }}"
        node2:
          vrrp_state: BACKUP
          vrrp_priority: 50
          vrrp_interface: "{{ ansible_eth0 }}"
        node3:
          vrrp_state: BACKUP
          vrrp_priority: 50
          vrrp_interface: "{{ ansible_eth0 }}"
...
